version: 1
disable_existing_loggers: true
root:
  handlers: [app_handler]
loggers:
  uvicorn:
    propagate: false
    level: INFO
    handlers: [uvicorn_handler]
handlers:
  app_handler:
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
    formatter: app_formatter
    filters: [trace_id]
  uvicorn_handler:
    class: logging.StreamHandler
    stream: "ext://sys.stdout"
    formatter: uvicorn_formatter
    filters: [trace_id]
formatters:
  app_formatter:
    (): "push_notifications_tools.logging.formatters.JsonFormatter.from_format_obj"
    format_obj:
      level: levelname
      timestamp: asctime
      trace_id: trace_id
      logger_name: name
      message: message
      details: details
  uvicorn_formatter:
    (): "push_notifications_tools.logging.formatters.JsonFormatter.from_format_obj"
    format_obj:
      level: levelname
      timestamp: asctime
      trace_id: trace_id
      logger_name: name
      message: message
filters:
  trace_id:
    (): "app.utils.logger.TraceIdFilter"
